# Assignment 3: LLMs and Machine Learning

---

## Submission Instructions

Submit only a link to the folder for Assignment 3 in your personal GitHub repository. Within the repository, you should have a Jupyter notebook file titled e.g. `assignment3.ipynb` or something similar, placed inside the `assignments/assignment3/` folder.

Make sure the repository is public.

**Submissions must be made using a GitHub repository. Submissions that do not follow this instruction will receive 0 points.**

**Late submissions are not accepted as the peer review system does not allow adding submissions past the deadline. Submit your work early to not miss the deadline!**

## Code Quality

Write your code so that it is pleasant to read and easy to understand. This includes:

- Use descriptive variable and function names.
- Add brief comments where the logic is not immediately obvious.
- Keep your notebook organized with clear separation between tasks.
- Print out your answers so that the peer reviewer can see the results. Use the `df.head()` when asked to print the top  5 lines. To print a better looking DataFrame, consider also using `display()` instead of `print()`.
- Divide the code into logical chunks. At minimum, use separate cells per task, and when reasonable, separate cells for subtasks.
- Remember to in the end rerun all code from the beginning to end of the notebook to ensure each cell runs without error

## Visualizations

In the visualizations always include enough information that the plot can be understood independently. This includes:

- Labels for both axes
- A descriptive title

## Statement of use of AI

Include a brief statement describing how and which AI was used (or if no AI was used) in completing the assignment. This could be a markdown cell with a couple of sentences. As a reminder, AI use is permitted in the assignments, but it is advisable to try to complete the tasks as far as possible without and to make sure you understand the code that AI produced when using it.

## Grading

This assignment is worth 10 points. Task 0 is worth 1 point, and tasks 1-2 are worth 2 points and task 3 is worth 5 points.

Points are given only for code that runs. If the code does not run, the task (or subtask if code for a task is divided into multiple cells) will automatically receive 0 points even if the code is almost correct.

### Penalties

- **-2 points per task** where AI-generated (hallucinated) data is used instead of the actual data provided in the task or retrieved from the specified source. The assignment requires working with real data, not made-up values!
- **-3 points** if an API key is included in the submission notebook or anywhere in the GitHub repository. Store your keys in a `.env` file and add `.env` to your `.gitignore`.
- **-1 point** if the Jupyter Notebook is overall messy and not structured well (e.g. if all tasks are completed within one cell, if answers are difficult to find due to too much irrelevant printed output).
- **-1 point** if there is no statement of AI use. If you did not use AI, report that you did not use AI.

### Editing the submission after the deadline

- Editing the assignment submission during the evaluation phase is forbidden. Thus, after the solution has been released, do not make any further changes to the notebook until you have received a grade. If you accidentally leaked an API key, revoke the key immediately. Other **changes to the submission are considered cheating, and will result in 0 points for both the assignment and peer review**.

---

## Tasks

### Task 0: Setting up Ollama (1p)

a) Set up Ollama and connect to it using either openAI's API or Ollama's own API. 

b) Load the 270m parameter version of the [gemma3](https://ollama.com/library/gemma3) model and test it with any prompt.

c) Load the 4b parameter version of the [gemma3](https://ollama.com/library/gemma3) and test it with any prompt. If running the 4b version is too slow, you can use the 1b version instead.

In [1]:
!ollama list

NAME             ID              SIZE      MODIFIED
gemma3:4b        a2af6cc3eb7f    3.3 GB    20 hours ago
gemma3:270m      e7d36fb2c3b3    291 MB    20 hours ago
gemma4:latest    c6eb396dbd59    9.6 GB    2 days ago

In [2]:
!pip install openai
!ollama pull gemma3:270m
!ollama pull gemma3:4b

from openai import OpenAI

client = OpenAI(
    base_url="http://localhost:11434/v1/",
    api_key="ollama"
)

MODEL = "gemma3:270m"

def ask(prompt):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

Requirement already satisfied: openai in c:\users\matts\anaconda3\lib\site-packages (2.33.0)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\matts\anaconda3\lib\site-packages (from openai) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\matts\anaconda3\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\matts\anaconda3\lib\site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\matts\anaconda3\lib\site-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\matts\anaconda3\lib\site-packages (from openai) (2.12.4)
Requirement already satisfied: sniffio in c:\users\matts\anaconda3\lib\site-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in c:\users\matts\anaconda3\lib\site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\matts\anaconda3\lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in c:\users\matts\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in c:\users\matts\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\matts\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\matts\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\matts\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\matts\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\matts\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: colorama in c:\users\matts\anaconda3\lib\site-packages (from tqdm>4->openai) (0.4.6)

pulling manifest â ‹ pulling manifest â ™ pulling manifest â ¹ pulling manifest â ¸ pulling manifest â ¼ pulling manifest â ´ pulling manifest â ¦ pulling manifest
pulling 735af2139dc6: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–� 291 MB
pulling 4b19ac7dd2fb: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–�  476 B
pulling 3e2c24001f9e: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–� 8.4 KB
pulling 339e884a40f6: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–�   61 B
pulling 74156d92caf6: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–�  490 B
verifying sha256 digest
writing manifest
success
pulling manifest â ‹ pulling manifest â ™ pulling manifest â ¹ pulling manifest â ¸ pulling manifest â ¼ pulling manifest â ´ pulling manifest â ¦ pulling manifest
pulling aeda25e63ebd: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–� 3.3 GB
pulling e0a42594d802: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–�  358 B
pulling dd084c7d92a3: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–� 8.4 KB
pulling 3116c5225075: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–�   77 B
pulling b6ae5839783f: 100% â–•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–�  489 B
verifying sha256 digest
writing manifest
success

In [3]:
#b)
MODEL = "gemma3:270m"
print(ask("Tell me something fun"))

That sounds like a great choice! 😄

In [4]:
#c) 
MODEL ="gemma3:4b"
print(ask("Tell me something fun"))

Okay, here’s a little something fun!

Did you know that otters hold hands while they sleep so they don’t drift apart?

Isn’t that adorable?! 😊

---

Would you like to hear another fun fact, or maybe I could:

*   Tell you a joke?
*   Suggest a quick game?

### Task 1: Text classification with Ollama (2p)

The `data/emails.csv` file contains 12 email headlines, with 4 spam emails, 4 legitimate work emails and 4 vague emails that are hard to classify based on the title alone. Use this dataset for all subtasks in this task.

a) Make a function for classifying emails (based on the headlines) as spam, work or unknown. The function should return only the classification and nothing else. (0.5p)

b) Use the smaller gemma3 (270m) to classify the emails using the function created in part a. (0.5p)

c) Use larger gemma3 (4b) to classify the emails using the function created in part a). In separate markdown cell, write a brief comment comparing the results of parts b) and c). (0.5p)

d) Write a script that repeats b) and c) 3 times, storing the results for both models separately. For both models, put the results as columns into a new DataFrame that also contains the headlines so that it is easy to compare how the output varied across runs for both models. Comment if there were differences and explain why this happened. (0.5p)

In [5]:
#a)
import pandas as pd

emails = pd.DataFrame({
    "email_id": [1,2,3,4,5,6,7,8,9,10,11,12],
    "email_header": ["URGENT: Your account will be suspended within 24 hours",
    "Congratulations! You have won a 1000â‚¬ gift card, claim now",
    "Hot singles in your area are waiting to meet you tonight",
    "Re: Inheritance transfer of 4.5M USD pending your approval",
    "Meeting agenda for Thursday's project review",
    "Q3 budget report attached, please review by Friday",
    "Reminder: Annual performance review scheduled for next week",
    "Updated draft of the manuscript, comments welcome",
    "Quick question about last week",
    "Following up",
    "Important update regarding your recent activity",
    "Are you available?"]
                     })

def classify_emails(text): 
    prompt = ( 
        f"Classify the email based on their headlines with exactly one word: " 
        f"Spam, Work, Unknown" 
        f"return the classifications, nothing else" 
        f"Headline: {text}" ) 

    result = ask(prompt).strip() 
    return result

In [6]:
#b)
MODEL ="gemma3:270m"
emails["classification"] = emails["email_header"].apply(classify_emails)
emails

    email_id                                       email_header classification
0          1  URGENT: Your account will be suspended within ...           Spam
1          2  Congratulations! You have won a 1000â‚¬ gift c...           Spam
2          3  Hot singles in your area are waiting to meet y...           Spam
3          4  Re: Inheritance transfer of 4.5M USD pending y...           Spam
4          5       Meeting agenda for Thursday's project review           Spam
5          6  Q3 budget report attached, please review by Fr...           Spam
6          7  Reminder: Annual performance review scheduled ...           Spam
7          8  Updated draft of the manuscript, comments welcome           Spam
8          9                     Quick question about last week           Spam
9         10                                       Following up
10        11    Important update regarding your recent activity           Spam
11        12                                 Are you available?    Unspecified

In [7]:
#c)
MODEL ="gemma3:4b"
emails["classification"] = emails["email_header"].apply(classify_emails)
emails

    email_id                                       email_header classification
0          1  URGENT: Your account will be suspended within ...           Spam
1          2  Congratulations! You have won a 1000â‚¬ gift c...           Spam
2          3  Hot singles in your area are waiting to meet y...           Spam
3          4  Re: Inheritance transfer of 4.5M USD pending y...           Work
4          5       Meeting agenda for Thursday's project review           Work
5          6  Q3 budget report attached, please review by Fr...           Work
6          7  Reminder: Annual performance review scheduled ...           Work
7          8  Updated draft of the manuscript, comments welcome           Work
8          9                     Quick question about last week        Unknown
9         10                                       Following up        Unknown
10        11    Important update regarding your recent activity           Spam
11        12                                 Are you available?           Spam

In [8]:
#The smaller model is not able to label almost any of the emails correctly, while the bigger model has very good guesses

In [9]:
#d)
Answers270m=[]
Answers4b = []

def classify270m(text):
    MODEL ="gemma3:270m"
    prompt = ( 
        f"Classify the email based on their headlines with exactly one word: " 
        f"Spam, Work, Unknown" 
        f"return the classifications, nothing else" 
        f"Headline: {text}" ) 

    result = ask(prompt).strip() 
    return result 

def classify4b(text):
    MODEL ="gemma3:4b"
    prompt = ( 
        f"Classify the email based on their headlines with exactly one word: " 
        f"Spam, Work, Unknown" 
        f"return the classifications, nothing else" 
        f"Headline: {text}" ) 

    result = ask(prompt).strip() 
    return result 

for answer in range(3):
    Answers270m.append(emails["email_header"].apply(classify270m))
    Answers4b.append(emails["email_header"].apply(classify4b))
    
results = pd.DataFrame({
    "headline": emails["email_header"],
    "run1_270m": Answers270m[0],
    "run2_270m": Answers270m[1],
    "run3_270m": Answers270m[2],
    "run1_4b": Answers4b[0],
    "run2_4b": Answers4b[1],
    "run3_4b": Answers4b[2]
})
results

,headline,run1_270m,run2_270m,run3_270m,run1_4b,run2_4b,run3_4b
0,URGENT: Your account will be suspended within ...,Spam,Spam,Spam,Spam,Spam,Spam
1,Congratulations! You have won a 1000â‚¬ gift c...,Spam,Spam,Spam,Spam,Spam,Spam
2,Hot singles in your area are waiting to meet y...,Spam,Spam,Spam,Spam,Spam,Spam
3,Re: Inheritance transfer of 4.5M USD pending y...,Work,Work,Work,Work,Work,Work
4,Meeting agenda for Thursday's project review,Work,Work,Work,Work,Work,Work
5,"Q3 budget report attached, please review by Fr...",Work,Work,Work,Work,Work,Work
6,Reminder: Annual performance review scheduled ...,Work,Work,Work,Work,Work,Work
7,"Updated draft of the manuscript, comments welcome",Work,Work,Work,Work,Work,Work
8,Quick question about last week,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
9,Following up,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
10,Important update regarding your recent activity,Spam,Spam,Spam,Spam,Spam,Spam
11,Are you available?,Spam,Spam,Spam,Spam,Spam,Spam

### Task 2: Sentiment analysis with Ollama (2p)

The `data/news.csv` file contains 10 fictional financial news headlines. Use it for all subtasks in this task.

a) Make a function for classifying the texts in the provided dataset based on the topic (earnings, mergers, regulation, macroeconomics) and for determining the sentiment of the news (positive, negative, neutral). The function should return the class and sentiment in JSON format. (1p)

b) Use gemma3 (4b) to classify and provide the sentiment for each row of the provided dataset, inserting them into a new DataFrame that contains both the original headlines as well as topic and sentiment. (0.5p)

c) Give the same data and prompt to a browser based LLM (e.g. ChatGPT, LeChat, Claude or Gemini) and ask it to provide the topic and sentiment, giving it the same options. Paste the results into a markdown cell. Compare the results of b) and c), which one is more accurate and why? (0.5p)

In [10]:
import json
News = pd.DataFrame(
    {"news_id": [1,2,3,4,5,6,7,8,9,10],
    "news_headlines": ["Nordion Industries beats Q1 earnings estimates as cloud revenue surges 28%",
                       "Helvora Pharmaceuticals misses earnings forecast amid weak generics demand",
                       "Aurelis Bank reports steady quarterly profit, in line with analyst expectations",
                       "Veridyne Logistics to acquire rival Trantec in 4.2 billion euro deal",
                       "Antitrust regulators block proposed merger between Solenta and Marvex Energy",
                       "Kestrel Semiconductor confirms early-stage merger talks with Aldenfeld AG",
                       "New EU AI Act compliance rules expected to raise costs for Lumavex by 12%",
                       "Finnish FSA grants Norvik Capital expanded licence for cross-border operations",
                       "Eurozone inflation cools to 2.1%, easing pressure on Drava Holdings borrowing costs",
                       "Rising interest rates weigh on Tessaro Real Estate as financing costs climb"]
})

#a)

def classifyNews(text):
    model = "gemma3:4b"
    prompt = f"""classify the texts in the provided dataset based on the topic (earnings, mergers, regulation, macroeconomics).
            Also include the sentiment of the news (positive, negative, neutral).
            Do not include any other text, markdown formatting, or code blocks. Return only the JSON object.
            review: {text}"""
    result = ask(prompt)
    cleaned = result.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
    return json.loads(cleaned)

In [11]:
#b) 
News["analysis"] = News["news_headlines"].apply(classifyNews)

News["topic"] = News["analysis"]
News["sentiment"] = News["analysis"]

result_df = News[["news_headlines", "topic", "sentiment"]]
result_df

,news_headlines,topic,sentiment
0,Nordion Industries beats Q1 earnings estimates...,[{'text': 'Nordion Industries beats Q1 earning...,[{'text': 'Nordion Industries beats Q1 earning...
1,Helvora Pharmaceuticals misses earnings foreca...,"[{'topic': 'earnings', 'sentiment': 'negative'}]","[{'topic': 'earnings', 'sentiment': 'negative'}]"
2,"Aurelis Bank reports steady quarterly profit, ...",[{'text': 'Aurelis Bank reports steady quarter...,[{'text': 'Aurelis Bank reports steady quarter...
3,Veridyne Logistics to acquire rival Trantec in...,"[{'topic': 'mergers', 'sentiment': 'positive'}...","[{'topic': 'mergers', 'sentiment': 'positive'}..."
4,Antitrust regulators block proposed merger bet...,[{'text': 'Antitrust regulators block proposed...,[{'text': 'Antitrust regulators block proposed...
5,Kestrel Semiconductor confirms early-stage mer...,[{'text': 'Kestrel Semiconductor confirms earl...,[{'text': 'Kestrel Semiconductor confirms earl...
6,New EU AI Act compliance rules expected to rai...,"[{'topic': 'regulation', 'sentiment': 'negativ...","[{'topic': 'regulation', 'sentiment': 'negativ..."
7,Finnish FSA grants Norvik Capital expanded lic...,"[{'topic': 'regulation', 'sentiment': 'neutral...","[{'topic': 'regulation', 'sentiment': 'neutral..."
8,"Eurozone inflation cools to 2.1%, easing press...","[{'topic': 'macroeconomics', 'sentiment': 'neu...","[{'topic': 'macroeconomics', 'sentiment': 'neu..."
9,Rising interest rates weigh on Tessaro Real Es...,"[{'topic': 'earnings', 'sentiment': 'negative'...","[{'topic': 'earnings', 'sentiment': 'negative'..."

In [12]:
from dotenv import load_dotenv
import os
load_dotenv("GeminiAPI.env")

api_key = os.environ.get("GEMINI_API_KEY")

if api_key:
    print(f"key loaded: {api_key[:5]}...")
else:
    print("Error: no Gemini API found")

key loaded: AIzaS...

In [13]:
!pip install google-genai
from google import genai

gemini_client = genai.Client(api_key = api_key)

def ask_gemini(prompt):
    response = gemini_client.models.generate_content(
        model="gemini-2.5-flash-lite",
        contents=prompt
    )
    return response.text

Requirement already satisfied: google-genai in c:\users\matts\anaconda3\lib\site-packages (1.75.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\users\matts\anaconda3\lib\site-packages (from google-genai) (4.10.0)
Requirement already satisfied: google-auth<3.0.0,>=2.48.1 in c:\users\matts\anaconda3\lib\site-packages (from google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.50.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in c:\users\matts\anaconda3\lib\site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in c:\users\matts\anaconda3\lib\site-packages (from google-genai) (2.12.4)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\users\matts\anaconda3\lib\site-packages (from google-genai) (2.32.5)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in c:\users\matts\anaconda3\lib\site-packages (from google-genai) (9.1.2)
Requirement already satisfied: websockets<17.0,>=13.0.0 in c:\users\matts\anaconda3\lib\site-packages (from google-genai) (16.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in c:\users\matts\anaconda3\lib\site-packages (from google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\matts\anaconda3\lib\site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in c:\users\matts\anaconda3\lib\site-packages (from google-genai) (1.3.0)
Requirement already satisfied: idna>=2.8 in c:\users\matts\anaconda3\lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\matts\anaconda3\lib\site-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\matts\anaconda3\lib\site-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (46.0.3)
Requirement already satisfied: certifi in c:\users\matts\anaconda3\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\matts\anaconda3\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\matts\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\matts\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\matts\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\matts\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\matts\anaconda3\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\matts\anaconda3\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.5.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\matts\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.0.0)
Requirement already satisfied: pycparser in c:\users\matts\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.23)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\matts\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.6.1)

In [14]:
def classifyNewsGemini(text):
    prompt = f"""classify the texts in the provided dataset based on the topic (earnings, mergers, regulation, macroeconomics).
            Also include the sentiment of the news (positive, negative, neutral).
            Do not include any other text, markdown formatting, or code blocks. Return only the JSON object.
            review: {text}"""
    result = ask_gemini(prompt)
    cleaned = result.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
    return json.loads(cleaned)

In [15]:
News["analysis"] = News["news_headlines"].apply(classifyNewsGemini)

News["topic"] = News["analysis"].apply(lambda x: x.get("topic", ""))
News["sentiment"] = News["analysis"].apply(lambda x: x.get("sentiment",""))

result_df = News[["news_headlines", "topic", "sentiment"]]
result_df

AttributeError: 'list' object has no attribute 'get'

news_headlines	topic	sentiment
0	Nordion Industries beats Q1 earnings estimates...	earnings	positive
1	Helvora Pharmaceuticals misses earnings foreca...	earnings	negative
2	Aurelis Bank reports steady quarterly profit, ...	earnings	neutral
3	Veridyne Logistics to acquire rival Trantec in...	mergers	neutral
4	Antitrust regulators block proposed merger bet...	mergers	negative
5	Kestrel Semiconductor confirms early-stage mer...	mergers	neutral
6	New EU AI Act compliance rules expected to rai...	regulation	negative
7	Finnish FSA grants Norvik Capital expanded lic...	regulation	neutral
8	Eurozone inflation cools to 2.1%, easing press...	macroeconomics	positive
9	Rising interest rates weigh on Tessaro Real Es...	macroeconomics	negative

### Task 3: Supervised machine learning (5p)

For this task, use a subset of the [Bank Marketing](https://archive.ics.uci.edu/dataset/222/bank+marketing) dataset, by downloading and importing the `bank-additional.csv` from the UCI repository. You can find a description of the dataset behind the link.

The goal is to predict whether a prospective customer will subscribe to a term deposit (variable y).

a) Import the dataset and conduct exploratory data analysis on it. (1p)

b) Preprocess the data using the appropriate methods as described in the course materials. (1p)

c) Determine whether this is a classification or regression task. Choose three different machine learning algorithms from scikit-learn and explain briefly why you chose them. For each of the selected algorithsm, train and a model and iteratively adjust the hyperparameters until you no longer manage to improve the performance. (1p)

d) Compare using train, validation and test set split versus using cross-validation. Which one performs better? (1p)

e) Report and evaluate the performance of the models using several of the metrics provided in the course, and explain which model is the best for the task and why. (1p)

In [ ]:
#a)
df_bank = pd.read_csv("C:/Users/matts/Documents/bank-additional/bank-additional/bank-additional-full.csv", sep=";")
df_bank.head()

In [ ]:
df_bank.describe()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(data=df_bank, x="y", hue="education")
plt.title("education vs subscription")

In [ ]:
#b)
df_bank = df_bank.replace("unknown", np.nan)
df_bank = df_bank.dropna()

In [ ]:
df_bank.head()

In [ ]:
df_bank.info()

In [ ]:
#One-hot encoding:
df_bank = pd.get_dummies(df_bank, columns=["marital"], drop_first=True, dtype=float)
df_bank = pd.get_dummies(df_bank, columns=["poutcome"], drop_first=True, dtype=float)
df_bank.head()

In [ ]:
#Label encoding
from sklearn.preprocessing import LabelEncoder
le_edu = LabelEncoder()
le_job = LabelEncoder()
le_day = LabelEncoder()
le_month = LabelEncoder()

df_bank["education"] = le_edu.fit_transform(df_bank["education"])
df_bank["job"] = le_edu.fit_transform(df_bank["job"])
df_bank["day_of_week"] = le_edu.fit_transform(df_bank["day_of_week"])
df_bank["month"] = le_edu.fit_transform(df_bank["month"])

In [ ]:
#numerical encoding
df_bank["y"] = df_bank["y"].map({"yes": 1, "no": 0})
df_bank["loan"] = df_bank["loan"].map({"yes": 1, "no": 0})
df_bank["default"] = df_bank["default"].map({"yes": 1, "no": 0})
df_bank["housing"] = df_bank["housing"].map({"yes": 1, "no": 0})
df_bank["contact"] = df_bank["contact"].map({"cellular": 1, "telephone": 0})

In [ ]:
df_bank.info()

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler_standard = StandardScaler()
df_bank[["age", "duration", "campaign", "pdays", "previous", "emp.var.rate", "cons.price.idx", "cons.conf.idx","euribor3m","nr.employed"]] = scaler_standard.fit_transform(df_bank[["age", "duration", "campaign", "pdays", "previous", "emp.var.rate", "cons.price.idx", "cons.conf.idx","euribor3m","nr.employed"]])

In [ ]:
#c) This is a classification task for predicting the people likely to subscribe.
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

X = df_bank.drop("y", axis=1)
y= df_bank["y"]

X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.2, random_state=42
)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)