In [ ]:
#Task 1:

In [2]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

In [38]:
valid_transactions = []
for transaction in transactions:
    if transaction["price"] != 0 and transaction["quantity"] >= 0:
        valid_transactions.append(transaction)
for transaction in valid_transactions:
    transaction["total"] = transaction["price"]*transaction["quantity"]

#grouping all valid transactions per region (dictionaries EU, US and APAC will only have valid transactions):

EU = []
for transaction in valid_transactions:
    if transaction["region"] == "EU":
        EU.append(transaction)
US = []
for transaction in valid_transactions:
    if transaction["region"] == "US":
        US.append(transaction)
APAC = []
for transaction in valid_transactions:
    if transaction["region"] == "APAC":
        APAC.append(transaction)

#making a new variable for each region to store their total revenues (EUtotal, UStotal and APACtotal):

EUtotal = 0
UStotal = 0
APACtotal = 0

for transaction in EU:
    EUtotal = EUtotal + transaction["total"]
    
for transaction in US:
    UStotal = UStotal + transaction["total"]

for transaction in APAC:
    APACtotal = APACtotal + transaction["total"]

#making a dictionary that stores the total revenues for every region:

total_per_region = [
    {"EU": EUtotal},
    {"US": UStotal},
    {"APAC": APACtotal},
]

#comparing the three possible outcomes:

if EUtotal >= UStotal and EUtotal >= APACtotal:
    print(f"The region with the highest revenue is EU with {EUtotal}")
elif UStotal >= EUtotal and UStotal >= APACtotal:
    print(f"The region with the highest revenue is US with {UStotal}")
else:
    print(f"The region with the highest revenue is APAC with {APACtotal}")

The region with the highest revenue is EU with 3600

In [ ]:
#Task 2:

In [ ]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

In [50]:
def summarise_sales(list):
    total = (sum(list))
    average = total / len(list)
    best_day = (max(list))
    worst_day = (min(list))
    above_average_count = 0
    
    for sale in list:
        if sale > average:
            above_average_count = above_average_count + 1

    sales_info = [
        {"total": total},
        {"average": average},
        {"best_day": best_day},
        {"worst_day": worst_day},
        {"above_average_count": above_average_count},
    ]
    return sales_info
result = summarise_sales(sales)
print(result)

[{'total': 20510}, {'average': 1465.0}, {'best_day': 2200}, {'worst_day': 870}, {'above_average_count': 7}]

In [ ]:
#Task 3

In [2]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

In [4]:
passing = []
for student in students:
    if student["grade"] >= 50:
        passing.append(student)
print(passing)

[{'name': 'Anna', 'grade': 85, 'attendance': 0.92}, {'name': 'Erik', 'grade': 58, 'attendance': 0.75}, {'name': 'Mia', 'grade': 91, 'attendance': 0.98}, {'name': 'Sara', 'grade': 72, 'attendance': 0.88}, {'name': 'Tom', 'grade': 67, 'attendance': 0.7}, {'name': 'Nina', 'grade': 95, 'attendance': 0.99}, {'name': 'Olli', 'grade': 50, 'attendance': 0.65}]

In [5]:
for student in students:
    if student["grade"]>=80:
        print(student["name"],": Excellent")
    elif student["grade"] < 80 and student["grade"] >=50:
        print(student["name"], ": Pass")
    else:
        print(student["name"], "Fail")

Anna : Excellent
Erik : Pass
Mia : Excellent
Leo Fail
Sara : Pass
Tom : Pass
Nina : Excellent
Olli : Pass

In [9]:
attendance_counter = 0
for student in students:
    if student["attendance"] >0.80:
        attendance_counter = attendance_counter + 1
print(f"there are {attendance_counter} students with an attendance rate of over 0.80")

there are 4 students with an attendance rate of over 0.80

In [13]:
best_student = students[0]
for student in students:
    if student["grade"]>best_student["grade"]:
        best_student = student
print(f"{best_student["name"]} had the highest grade; {best_student["grade"]}")

Nina had the highest grade; 95

In [19]:
#Making new lists "grades" and "student_names" with only the grades and names:

grades=[]
student_names=[]
for student in students:
    grades.append(student["grade"])
    student_names.append(student["name"])
    
highest_grade = max(grades)
#The highest grade and the top student have the same "index place" on the lists:
top_student = student_names[grades.index(max(grades))]
print(f"{top_student} had the highest grade; {highest_grade}")

Nina had the highest grade; 95

In [36]:
#Task 4:

class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}
    def add_asset(self, ticker, shares, price_per_share):
        self.holdings[ticker] = {
            "shares": shares,
            "price_per_share": price_per_share
        }
    def total_value(self):
        total = 0
        for asset in self.holdings.values():
            total = total + asset["shares"] * asset["price_per_share"]
        return total

    def most_valuable(self):
        top_ticker = None
        max_value = 0

        for ticker, asset in self.holdings.items():
            value = asset["shares"] * asset["price_per_share"]
            if value > max_value:
                max_value = value
                top_ticker = ticker

        return top_ticker
    
    def __str__(self):
        return(
            f"Owner: {self.owner}, "
            f"Number of assets: {len(self.holdings)},"
            f"Total value:, {self.total_value()}"
        )

p = Portfolio("User")

p.add_asset("ABC", 40, 100)
p.add_asset("CBA", 33, 22)
p.add_asset("NVDA", 3, 200)

print(p)
print(f"total value of portfolio:  {p.total_value()}")
print(f"most valuable asset: {p.most_valuable()}")

Owner: User, Number of assets: 3,Total value:, 5326
total value of portfolio:  5326
most valuable asset: ABC

In [50]:
#Task 5:

import datetime
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]
dates = []
for date, product in orders:
    #because datetime.date does not work with strings (the format the dates are currently in), 
    #we must first make them integers
    year = int(date[0:4])
    month = int(date[5:7])
    day = int(date[8:10])
    date_integers = datetime.date(year, month, day)
    dates.append(date_integers)

time_between = max(dates) - min(dates)
print(time_between)

80 days, 0:00:00

In [66]:
#Task 6:

import numpy as np
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

total_revenue = np.sum(revenue, axis=1)
print(f"the total revenues per year are {total_revenue}")

mean_revenue = np.mean(revenue, axis=1)
print(f"the total mean revenues per year are {mean_revenue}")

growth = np.array([1.05, 1.03, 1.08, 1.02])
grown_2024 = revenue[2] * growth
print(f"the 2024 revenues with the growth adjustments are {grown_2024}")

#printing all quarterly revenues over 250
over_250 = revenue > 250
print(over_250)

the total revenues per year are [ 880  950 1080]
the total mean revenues per year are [220.  237.5 270. ]
the 2024 revenues with the growth adjustments are [262.5 298.7 248.4 316.2]
[[False False False False]
 [False  True False  True]
 [False  True False  True]]

In [98]:
#Task 7:

import pandas as pd
data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}
df_data = pd.DataFrame(data)
df_data["salary_per_year_exp"] = (df_data["salary"]/df_data["years_exp"])
df_data
sorted_data = df_data.sort_values(by="performance_score", ascending=False)
#to get the top 3 worst performing employees:
print(sorted_data.head(3))

over_4_finance = df_data.loc[
    (df_data["department"] == "Finance") &
    (df_data["performance_score"] > 4.0)
]
print(over_4_finance)
df_data = df_data.rename(columns = {"years_exp": "experience_years"})
df_data

  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9
2      Mia    Finance    4800          7                4.5
0     Anna    Finance    4500          5                4.2

   salary_per_year_exp
5           637.500000
2           685.714286
0           900.000000
  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2
2      Mia    Finance    4800          7                4.5

   salary_per_year_exp
0           900.000000
2           685.714286

,employee,department,salary,experience_years,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900.000000
1,Erik,Marketing,4000,3,3.8,1333.333333
2,Mia,Finance,4800,7,4.5,685.714286
3,Leo,IT,5200,10,4.0,520.000000
4,Sara,Marketing,3900,2,3.5,1950.000000
5,Tom,IT,5100,8,4.9,637.500000

In [100]:
print(df_data.iloc[ :4, [2,4]])

   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0

In [ ]:
#Task 8:

In [104]:
rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

df = pd.DataFrame({
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
}, index=days)

df.index.name = "date"

df["conversions"] = (df["visitors"] * df["conversion_rate"]).round().astype(int)
df["daily_revenue"] = df["conversions"] * df["avg_order_value"]

df

,visitors,conversion_rate,avg_order_value,conversions,daily_revenue
date,,,,,
2025-01-06,206,0.0645,64.30,13,835.90
2025-01-07,472,0.0578,48.44,27,1307.88
2025-01-08,437,0.0756,43.26,33,1427.58
2025-01-09,221,0.0339,43.61,7,305.27
2025-01-10,563,0.0679,49.39,38,1876.82
2025-01-11,288,0.0511,46.07,15,691.05
2025-01-12,302,0.0339,72.90,10,729.00
2025-01-13,273,0.0300,42.82,8,342.56
2025-01-14,333,0.0499,50.33,17,855.61
2025-01-15,270,0.0550,50.28,15,754.20
2025-01-16,339,0.0311,50.28,11,553.08
2025-01-17,524,0.0209,50.55,11,556.05
2025-01-18,380,0.0483,45.18,18,813.24
2025-01-19,569,0.0637,44.17,36,1590.12
2025-01-20,379,0.0751,41.38,28,1158.64
2025-01-21,310,0.0575,35.12,18,632.16
2025-01-22,515,0.0750,52.16,39,2034.24
2025-01-23,527,0.0719,59.84,38,2273.92
2025-01-24,544,0.0331,44.57,18,802.26
2025-01-25,555,0.0720,44.41,40,1776.40
2025-01-26,210,0.0638,46.84,13,608.92
2025-01-27,405,0.0367,45.39,15,680.85
2025-01-28,307,0.0678,35.64,21,748.44
2025-01-29,297,0.0719,63.65,21,1336.65
2025-01-30,296,0.0380,54.39,11,598.29
2025-01-31,529,0.0516,42.88,27,1157.76
2025-02-01,516,0.0243,52.97,13,688.61
2025-02-02,285,0.0550,45.62,16,729.92